name: mewinder
description: "Mewinder — приложение в стиле Tinder для просмотра котиков, лайков и изучения пород. Использует TheCatAPI, swipe-жесты, локальное сохранение лайков и список пород."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP-клиент для запросов к TheCatAPI
  http: ^1.2.2

  # Кеширование и плавная загрузка картинок
  cached_network_image: ^3.4.1
  
  # Для работы с .env и скрытия приватных ключей
  flutter_dotenv: ^6.0.0

  # Локальное хранилище 
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Набор линтов от Flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
